import customtkinter as ctk
import threading
import time
import webbrowser
import os
import shutil
import json
import platform
import subprocess
from pathlib import Path
from gui.theme import *
from config import BASE_DIR, OPENCLAW_IMAGE

class ScreenInstall(ctk.CTkFrame):
    def __init__(self, master, on_finish, on_prev, install_data, **kwargs):
        super().__init__(master, fg_color=BG_COLOR, **kwargs)
        self.on_finish = on_finish
        self.on_prev = on_prev
        self.install_data = install_data

        self.title = ctk.CTkLabel(self, text="Installing OpenClaw...", font=FONT_HEADING, text_color=TEXT_COLOR)
        self.title.pack(pady=(20, 10))

        self.progress = ctk.CTkProgressBar(self, width=600, height=15, progress_color=ACCENT_COLOR)
        self.progress.pack(pady=10)
        self.progress.set(0)

        self.log_box = ctk.CTkTextbox(self, width=600, height=300, font=FONT_MONO, fg_color=PANEL_BG, text_color=MUTED_TEXT, state="disabled")
        self.log_box.pack(pady=10, padx=20)

        self.btn_frame = ctk.CTkFrame(self, fg_color="transparent")
        self.btn_frame.pack(pady=20)

        self.btn_dashboard = ctk.CTkButton(self.btn_frame, text="Open Dashboard", command=self.open_dashboard, fg_color=SUCCESS_COLOR, text_color=BG_COLOR, state="disabled")
        self.btn_dashboard.pack(side="left", padx=10)

        self.btn_folder = ctk.CTkButton(self.btn_frame, text="Open Install Folder", command=self.open_folder, fg_color=PANEL_BG, text_color=TEXT_COLOR, state="disabled")
        self.btn_folder.pack(side="left", padx=10)

        self.btn_finish = ctk.CTkButton(self.btn_frame, text="Finish", command=self.on_finish, fg_color=PANEL_BG, text_color=TEXT_COLOR, state="disabled")
        self.btn_finish.pack(side="left", padx=10)

        self.after(1000, self.start_install)

    def log(self, text):
        self.after(0, self._do_log, text)

    def _do_log(self, text):
        self.log_box.configure(state="normal")
        self.log_box.insert("end", f"[{time.strftime('%H:%M:%S')}] {text}\n")
        self.log_box.see("end")
        self.log_box.configure(state="disabled")

    def start_install(self):
        threading.Thread(target=self._do_install, daemon=True).start()

    def _do_install(self):
        from utils import docker_manager, shortcut_creator, health_check

        try:
            install_dir = Path(self.install_data.get("install_dir", "."))
            port = self.install_data.get("port", 3000)
            models = self.install_data.get("models", [])
            agents = self.install_data.get("agents", [])
            telegram = self.install_data.get("telegram_enabled", False)
            tg_token = self.install_data.get("telegram_token", "")
            tg_chat = self.install_data.get("telegram_chat_id", "")

            # 1. Create directory structure
            self.log(f"Creating directory structure at {install_dir}...")
            install_dir.mkdir(parents=True, exist_ok=True)
            (install_dir / "workspace").mkdir(exist_ok=True)
            (install_dir / "agents").mkdir(exist_ok=True)
            (install_dir / "logs").mkdir(exist_ok=True)
            (install_dir / "assets").mkdir(exist_ok=True)
            self.progress.set(0.1)

            # 1.5 Save icons
            self.log("Saving icons...")
            try:
                import base64
                from assets.icons import CLAW_ICO_B64, CLAW_PNG_B64
                with open(install_dir / "assets" / "claw.ico", "wb") as f:
                    f.write(base64.b64decode(CLAW_ICO_B64))
                with open(install_dir / "assets" / "claw.png", "wb") as f:
                    f.write(base64.b64decode(CLAW_PNG_B64))
            except Exception as e:
                self.log(f"Warning: Failed to save icons: {e}")

            # 2. Copy templates using absolute paths
            self.log("Copying configuration files...")
            template_dir = BASE_DIR / "templates"
            files_to_copy = ["docker-compose.yml", "launcher.pyw", "telegram_notifier.py"]
            for f_name in files_to_copy:
                src = template_dir / f_name
                if src.exists():
                    shutil.copy(src, install_dir / f_name)
                    self.log(f"Copied {f_name}")
                else:
                    self.log(f"Warning: Template {f_name} not found at {src}")
            self.progress.set(0.2)

            # 3. Write .env file
            self.log("Writing .env file...")
            default_agent = agents[0] if agents else 'FullStack Dev'
            default_model = models[0] if models else 'llama3.2:8b'
            
            env_content = f"""# OpenClaw Environment Configuration
# Auto-generated by ClawSetup

WORKSPACE_BASE={install_dir / "workspace"}
OPENCLAW_PORT={port}
OPENCLAW_IMAGE={OPENCLAW_IMAGE}

OLLAMA_API_URL=http://127.0.0.1:11434/api
DEFAULT_AGENT={default_agent}
DEFAULT_MODEL={default_model}

TELEGRAM_BOT_TOKEN={tg_token if telegram else ''}
TELEGRAM_CHAT_ID={tg_chat if telegram else ''}
TELEGRAM_NOTIFY_START={str(telegram).lower()}
TELEGRAM_NOTIFY_COMPLETE={str(telegram).lower()}
TELEGRAM_NOTIFY_FAIL={str(telegram).lower()}
TELEGRAM_NOTIFY_SWITCH={str(telegram).lower()}
TELEGRAM_NOTIFY_FILE={str(telegram).lower()}
"""
            with open(install_dir / ".env", "w") as f:
                f.write(env_content)
            self.progress.set(0.3)

            # 4. Pull OpenClaw Docker image
            self.log(f"Pulling {OPENCLAW_IMAGE} (may take time)...")
            docker_manager.pull_image(OPENCLAW_IMAGE, self.log)
            self.progress.set(0.5)

            # 5. Copy agent profiles
            self.log("Copying agent profiles...")
            agents_src = template_dir / "agents"
            if agents_src.exists():
                for agent_file in agents_src.glob("*.json"):
                    shutil.copy(agent_file, install_dir / "agents" / agent_file.name)
            self.progress.set(0.6)

            # 6. Create desktop shortcut
            self.log("Creating desktop shortcut...")
            launcher_path = install_dir / "launcher.pyw"
            shortcut_creator.create_desktop_shortcut(str(launcher_path), "OpenClaw")
                
            if platform.system() == "Windows":
                # 6.5 Configure Firewall
                self.log("Configuring Windows Firewall...")
                try:
                    from platforms.windows.firewall_windows import configure_firewall
                    configure_firewall(port, self.log)
                except Exception as e:
                    self.log(f"Warning: Failed to configure firewall: {e}")
            self.progress.set(0.7)

            # 7. Save installation state
            self.log("Saving installation state...")
            state_file = Path.home() / ".clawsetup_state.json"
            state_data = {
                "installed": True,
                "install_dir": str(install_dir),
                "port": port,
                "models": models,
                "agents": agents,
                "telegram": telegram
            }
            with open(state_file, "w") as f:
                json.dump(state_data, f)
            self.progress.set(0.8)

            # 7.5 Start Docker Compose
            self.log("Starting OpenClaw container...")
            try:
                # Use absolute path to docker compose just in case
                subprocess.run(["docker", "compose", "up", "-d"], cwd=str(install_dir), check=True, capture_output=True)
                self.log("Docker Compose initiated successfully.")
            except Exception as e:
                self.log(f"Warning: Failed to start container automatically: {e}")
            self.progress.set(0.9)

            # 8. Run first-time health check
            self.log("Running health check...")
            # Note: Health check will be fixed later to handle JSON key differences
            health_results = health_check.run_health_check(port, install_dir, agents)
            for res in health_results:
                self.log(f"  - {res['name']}: {'OK' if res['status'] else 'FAILED'}")
                if not res['status'] and res['suggestion']:
                    self.log(f"    Suggestion: {res['suggestion']}")
            self.progress.set(1.0)

            self.log("Installation complete!")
            self.title.configure(text="✅ OpenClaw is ready!", text_color=SUCCESS_COLOR)
            
            self.btn_dashboard.configure(state="normal")
            self.btn_folder.configure(state="normal")
            self.btn_finish.configure(state="normal", fg_color=ACCENT_COLOR, text_color=BG_COLOR)

        except Exception as e:
            self.log(f"ERROR: {str(e)}")
            self.title.configure(text="❌ Installation Failed", text_color=ERROR_COLOR)
            self.btn_finish.configure(state="normal", fg_color=ERROR_COLOR, text_color=BG_COLOR)
            import traceback
            self.log(traceback.format_exc())

    def open_dashboard(self):
        port = self.install_data.get("port", 3000)
        webbrowser.open(f"http://localhost:{port}")

    def open_folder(self):
        path = self.install_data.get("install_dir", ".")
        if platform.system() == "Windows":
            os.startfile(path)
        elif platform.system() == "Darwin":
            import subprocess
            subprocess.Popen(["open", path])
